version: '3'
services:
  jenkins:
    image: jenkins:latest
    ports:
      - "${SERVICE_JENKINS_PORT}"
      - "50000:50000"
    working_dir: /var/jenkins_home
    volumes:
       - "${SERVICE_JENKINS_VOLUME_HOST}:/var/jenkins_home"
    extra_hosts:
      - "dockerhost:${SERVICE_JENKINS_DOCKERHOST}"
    env_file:
      - jenkins/.env
    restart: on-failure

  nginx:
    image: nginx
    volumes:
      - /opt/nginx/config:/etc/nginx/conf.d
      - /opt/nginx/logs:/etc/nginx/logs
      - /opt/letsencrypt/certbot:/etc/letsencrypt
    links:
      - jenkins
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - nginx/.env
    restart: on-failure

  certbot:
    image: certbot/certbot
    volumes:
      - /opt/letsencrypt/certbot:/etc/letsencrypt
      - /opt/letsencrypt/logs:/var/log/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    command: certonly --standalone --non-interactive --agree-tos --email=${SERVICE_CERTBOT_EMAIL} ${SERVICE_CERTBOT_DOMAINS}